### ISSUE TITLE
TODO - 20151027

### ISSUE THREAD

**Issue by soohan-ahn** [soohanboys/eagles#7]
- [x] Add the stats for batter.
- RBI
- Run
- Sacrificed records.
- [x] Implement the multiple records per an inning for the batters.
- [x] Configuration for the deploy to the AWS.
- AWS EC2.
- Unicorn
- Nginx
- http://qiita.com/Yama-to/items/1e1d889e6d5f7cc7f281
- [x] Tuning the SQL query.
- [ ] Personal detailed records.
- [ ] Add the redis server.
- [x] Add the bootstrap or good looking front-end tools.
